// GENERATED from server/src/constants/regions.js — do not edit by hand.
// One list shared by both sides: a region typed differently in two places would
// split one market into two rows in the regional report.
export const TZ_REGIONS = [
  "Arusha",
  "Dar es Salaam",
  "Dodoma",
  "Geita",
  "Iringa",
  "Kagera",
  "Katavi",
  "Kigoma",
  "Kilimanjaro",
  "Lindi",
  "Manyara",
  "Mara",
  "Mbeya",
  "Morogoro",
  "Mtwara",
  "Mwanza",
  "Njombe",
  "Pwani",
  "Rukwa",
  "Ruvuma",
  "Shinyanga",
  "Simiyu",
  "Singida",
  "Songwe",
  "Tabora",
  "Tanga",
  "Kaskazini Pemba (Pemba North)",
  "Kaskazini Unguja (Unguja North)",
  "Kusini Pemba (Pemba South)",
  "Kusini Unguja (Unguja South)",
  "Mjini Magharibi (Urban West)",
];
